### ISSUE TITLE
Amiga 500 -colors are displayed incorrectly | black is dark red

### ISSUE THREAD

**Issue by sascha70** [IanSB/RGBtoHDMI#13]
Hello community,

unfortunately a bug is driving me crazy with the Amiga 500. 

Unfortunately, the colors are displayed somewhat incorrectly for me. What should be black is dark red. I used the Beta54 version from JanBeta and the version from main tree 20211224_c97f06a release. All have the same problem. The adapter is from LinuxJedi (https://github.com/LinuxJedi/AmigaRGBtoHDMI/tree/main/Amiga500CPLD).

Do you have a solution?

Thanks

sascha
![capture8](https://user-images.githubusercontent.com/106908158/172044394-bd3de467-68fc-4db4-8226-f77ee9b0bdfc.png)
a

**Comment by solarmon** [comment]
Looks like one of the red signal is missing or shorted together? I would inspect and check the soldering of the red signals and traces on the adapter itself.

Did you build the adapter yourself?

**Comment by sascha70** [comment]
> Looks like one of the red signal is missing or shorted together? I would inspect and check the soldering of the red signals and traces on the adapter itself.
> 
> Did you build the adapter yourself?
> 
> Also, check whether you get the same issue on the RGB video output.

They were right. It was the plug-in lead from the Pi Zero. I checked it with a Pi 3 A+ and it worked great. 

Thanks for your great project!

Greetings

Sascha
