### ISSUE TITLE
Scanlines are not working (C64)

### ISSUE THREAD

**Issue by InsertDiskTwo** [IanSB/RGBtoHDMI#23]
No scanlines when I enable the option in the menu. Also tried long-holding SW1, it says that scanlines are on, but there are none. Tried all the different scanline options 1 to 14. Nothing works. I am using the latest beta version.

Thank you!

**Comment by IanSB** [comment]
@InsertDiskTwo 

Can you try the latest Alpha 61H from here:

https://github.com/IanSB/RGBtoHDMI/issues/21#issuecomment-1803126290

**Comment by InsertDiskTwo** [comment]
This worked, thanks!
    On Friday, 10 November 2023 at 20:17:34 CET, IanSB ***@***.***> wrote:  
 
 


@InsertDiskTwo

Can you try the latest Alpha 61H from here:

#21 (comment)

**Comment by IanSB** [comment]
@InsertDiskTwo 
beta 61 now available with that fix:
https://github.com/IanSB/RGBtoHDMI/releases

**Comment by InsertDiskTwo** [comment]
Awesome thanks! 

Sent from Yahoo Mail on Android 
 
  On Sun, 12 Nov 2023 at 18:39, ***@***.***> wrote:   


@InsertDiskTwo
beta 61 now available with that fix:
https://github.com/IanSB/RGBtoHDMI/releases
