### ISSUE TITLE
PAL Atari 65XE noisy video. Menu good. 

### ISSUE THREAD

**Issue by sideburn** [IanSB/RGBtoHDMI#34]
I have a 65XE PAL and the video is noisy. Using most current firmware. Using Atari 800 lumacode (unterm) profile, and Atari 800 PAL palette. 

Tried tweaking all settings I can think of but no luck. 

![IMG_9253](https://github.com/user-attachments/assets/81171649-a879-4bbe-af90-8502a4a37dbb)
![IMG_9252](https://github.com/user-attachments/assets/de70842f-4f1e-43cd-af4f-ce44b82e9c13)
![IMG_9255](https://github.com/user-attachments/assets/5a879567-02b9-4f2a-afe0-0eedd9ed90e4)

video: http://sideburn.com/vid/lunacode.MOV

**Comment by IanSB** [comment]
Atari noise issue answered in: https://github.com/c0pperdragon/LumaCode/issues/2#issuecomment-2295241781
