### ISSUE TITLE
BOM Atari 12bit buffered pickup

### ISSUE THREAD

**Issue by md66pt** [IanSB/RGBtoHDMI#4]
Hi, first I want to thank you very much for your great work! I love this project and already have built one for C64 and Amiga 500.

Please let me ask you, if there is a BOM for the Atari ST 12bit unbuffered pickup board? I see two ic's and two caps at the gerbers.

I am restoring a 1040 STFM right now and would like to build one for it!

Thanks in advance, regards Wolfgang.

**Comment by md66pt** [comment]
Sorry, found it in the Atari ST discussion #6!

**Comment by mikrosk** [comment]
Just for future reference, he meant https://github.com/c0pperdragon/Amiga-Digital-Video/issues/6
