### ISSUE TITLE
Atari MegaSTE issue

### ISSUE THREAD

**Issue by Biker1bob** [IanSB/RGBtoHDMI#8]
I have built one of the devices up with a 12bit board I purchased assembled - its an IanSB board.

This is the topic thread I am getting my info from https://www.atari-forum.com/viewtopic.php?t=40201

My situation is - in LOW or MEDIUM resolution - where I would use the RGB colour (AKA NOT MONO) Green is substituted for Black - I cannot get the device to produce a BLACK - It is using the STE 50hz profile. My monitor is able to do 50hz. EVERYTHING else looks fine except where a black should be there is Green.

I have adjust every setting in the software I can think of. I have rechecked all my wiring 10+ times.. I am at a loss. Any suggestions would be appreciated

I have posted this in the main Github for the project. - just thought I would post here as well incase some only follow this fork.
![20220122_152133](https://user-images.githubusercontent.com/33105915/151198572-27b7dff7-3c1b-400c-89d5-5b122ded89c0.jpg)

**Comment by IanSB** [comment]
Addressed here:

https://github.com/hoglet67/RGBtoHDMI/issues/268
